name: Download competitive-verifier verify_files.json artifact
description: "A wrapper of actions/download-artifact for verify_files.json of competitive-verifier."
author: "Kzrnm"
branding:
  color: blue
  icon: download-cloud
inputs:
  artifact-name:
    description: The name of artifact which contains verify files json.
    required: false
    default: ${{ runner.os }}-verify-files-json
  artifact-root:
    description: Artifacts path.
    required: false
    default: ${{runner.temp}}/.verifier.artifacts
  download-all:
    description: "If true, the action download all artifacts."
    required: false
    default: "false"
  set-env:
    description: If true, set verify_files.json path to $COMPETITIVE_VERIFY_FILES_PATH
    required: false
    default: "true"
  working-directory:
    description: Specifies the working directory where the command is run.
    required: false
outputs:
  artifacts-root:
    description: Artifacts directory
    value: ${{steps.artifact-path.outputs.artifact-root}}
  json-path:
    description: verify_files.json path
    value: ${{steps.path.outputs.file}}
runs:
  using: composite
  steps:
    - name: Path
      id: artifact-path
      shell: pwsh
      working-directory: ${{inputs.working-directory}}
      run: |
        $output = (New-Item -Type Directory "${{ inputs.artifact-root }}" -Force).FullName
        echo "artifact-root=$output" >> $env:GITHUB_OUTPUT

    - name: Download artifact
      uses: actions/download-artifact@v4
      if: ${{!fromJSON(inputs.download-all)}}
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ steps.artifact-path.outputs.artifact-root }}/${{ inputs.artifact-name }}
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      if: ${{fromJSON(inputs.download-all)}}
      with:
        path: ${{ steps.artifact-path.outputs.artifact-root }}

    - name: Validate
      shell: bash
      id: validate
      working-directory: ${{inputs.working-directory}}
      run: |
        file="$(echo $COMPETITIVE_root/*)"
        echo "$file"
        if [ ! -f "$file" ] ; then
          echo "::error::file must be single file."
          exit 1
        fi
        if ! jq . "$file" ; then
          echo "::error::file must be json file."
          exit 2
        fi
        echo "file=$file" >> $GITHUB_OUTPUT
      env:
        COMPETITIVE_root: ${{ steps.artifact-path.outputs.artifact-root }}/${{ inputs.artifact-name }}

    - name: Path
      id: path
      shell: pwsh
      working-directory: ${{inputs.working-directory}}
      run: |
        $output = (Get-Item "${{steps.validate.outputs.file}}").FullName
        echo "file=$output" >> $env:GITHUB_OUTPUT

    - name: Set $COMPETITIVE_VERIFY_FILES_PATH
      if: ${{fromJSON(inputs.set-env)}}
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        echo "COMPETITIVE_VERIFY_FILES_PATH=${{steps.path.outputs.file}}" >> $GITHUB_ENV
