name: Test parse-doxygen
on:
  push:
    branches:
      - main
    paths:
      - parse-doxygen/**
      - .github/workflows/test-parse-doxygen.yml
  pull_request:
    paths:
      - parse-doxygen/**
      - .github/workflows/test-parse-doxygen.yml
  workflow_dispatch:

jobs:
  npm-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./parse-doxygen

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: parse-doxygen/.node-version
          cache-dependency-path: parse-doxygen/package-lock.json

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy test file
        run: cp parse-doxygen/__tests__/verify_files.json "$RUNNER_TEMP/verify-files.json"

      - name: parse-doxygen
        uses: ./parse-doxygen
        with:
          verify-files: ${{runner.temp}}/verify-files.json

      - name: Test
        run: diff "$RUNNER_TEMP/verify-files.json" parse-doxygen/__tests__/expected.json

      - name: sed subdir test file
        run: |
          sed -e 's|parse-doxygen/__tests__/||g' parse-doxygen/__tests__/verify_files.json > $RUNNER_TEMP/sub-verify-files.json
          sed -e 's|parse-doxygen/__tests__/||g' parse-doxygen/__tests__/expected.json > $RUNNER_TEMP/sub-expected.json

      - name: parse-doxygen subdir
        uses: ./parse-doxygen
        with:
          verify-files: ${{runner.temp}}/sub-verify-files.json
          working-directory: parse-doxygen/__tests__

      - name: Test subdir
        run: diff "$RUNNER_TEMP/sub-verify-files.json" "$RUNNER_TEMP/sub-expected.json"